version: "3.8"

services:
  ticketproxy:
    container_name: ticket-proxy
    image: nginx:1.21-alpine
    depends_on:
      - "ticketclient"
    volumes:
      - ./TicketProxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "7000:80"

  ticketclient:
    container_name: ticket-client
    build:
      context: ./TicketClient
    restart: always

  ticketapi:
    container_name: ticket-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=ticketdb,1433;Initial Catalog=TicketDb;User ID=SA;Password=49R8MXw#49c6wT9Q8!
    build:
      context: ./TicketApi
    restart: always
    depends_on:
      - "rabbitmq"
      - "ticketdb"

  ticketsender:
    container_name: ticket-sender
    build:
      context: ./TicketSender
    environment:
      - CHECK_HOST=rabbitmq
      - CHECK_PORT=5672
    restart: always
    depends_on:
      - "rabbitmq"

  ticketdb: # login SA:49R8MXw#49c6wT9Q8!
    container_name: ticket-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "49R8MXw#49c6wT9Q8!"
      MSSQL_PID: "Express"
    restart: always
    ports:
      - "1433:1433"

  rabbitmq: # login guest:guest
    container_name: ticket-rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
